        $exceptions->context(fn () => [
            'current_url' => request()->url(),
        ]);

        $exceptions->render(function (NotFoundHttpException $e, Request $request) {
            if ($request->is('api/*') || $request->is('local/*')) {
                return response()->json([
                    'message' => __('Record not found.')
                ], 404);
            }
        });